# Generated by Django 5.0.6 on 2024-06-22 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Colectivo',
                'verbose_name_plural': 'Colectivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Parada de autobus',
                'verbose_name_plural': 'Paradas de autobus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRAIN_ONLY', 'Train Only'), ('BUS_AND_TRAIN', 'Bus and Train')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado'), ('s', 'Suspendido'), ('f', 'Finalizado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Mercaderia',
                'verbose_name_plural': 'Mercaderias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dni_or_passport', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('w', 'Female')], default='m', help_text='Disponibilidad del Ejemplar', max_length=1)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['dni_or_passport'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Ventas',
                'ordering': ['ticket'],
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Categoria de Asiento',
                'verbose_name_plural': 'Categorias de Asiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Estacion',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField()),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'Tren',
                'verbose_name_plural': 'Trenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JourneySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journey')),
            ],
            options={
                'verbose_name': 'Cronograma de Recorrido',
                'verbose_name_plural': 'Cronogramas de Recorrido',
                'ordering': ['journey'],
            },
        ),
        migrations.CreateModel(
            name='DetailsMerchandiseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.merchandise')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_receipt', to='core.purchasereceipt')),
            ],
            options={
                'verbose_name': 'Detalle de la Orden de mercadería',
                'verbose_name_plural': 'Detalles de la Orden de mercadería',
                'ordering': ['receipt'],
            },
        ),
        migrations.CreateModel(
            name='DetailFoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_receipt', to='core.purchasereceipt')),
            ],
            options={
                'verbose_name': 'Detalle de la Orden de platos',
                'verbose_name_plural': 'Detalles de la Orden de platos',
                'ordering': ['receipt'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_reserved', models.BooleanField(default=False)),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado'), ('v', 'Vendido'), ('r', 'Devuelto')], default='h', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.seatcategory')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.train')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['seat_number'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journeyschedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['purchase_date'],
            },
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='core.ticket'),
        ),
        migrations.CreateModel(
            name='JourneyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
                ('end_bus_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_stages', to='core.busstop')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.journey')),
                ('start_bus_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_stages', to='core.busstop')),
                ('end_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_stages', to='core.station')),
                ('start_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_stages', to='core.station')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
            options={
                'verbose_name': 'Etapa de Recorrido',
                'verbose_name_plural': 'Etapas de Recorrido',
                'ordering': ['order'],
            },
        ),
    ]
