# Generated by Django 5.0.6 on 2024-06-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'ordering': ['name'], 'verbose_name': 'Parada de colectivo', 'verbose_name_plural': 'Paradas de colectivo'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['type'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorrido'},
        ),
        migrations.AddField(
            model_name='journey',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1),
        ),
    ]
