# Generated by Django 5.0.6 on 2024-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_busstop_options_alter_journey_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['type'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorridos'},
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
