# Generated by Django 5.0.6 on 2024-06-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_journey_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatcategory',
            old_name='price_multiplier',
            new_name='price',
        ),
    ]
