# Generated by Django 5.0.6 on 2024-06-22 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ticket_user_ticketsales_ticket_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
