# Generated by Django 5.0.6 on 2024-06-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_purchasereceipt_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfoodorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detailsmerchandiseorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
