# Generated by Django 5.0.6 on 2024-06-30 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ticket_sale_alter_ticketsales_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['purchase_date'], 'verbose_name': 'Factura de Venta', 'verbose_name_plural': 'Facturas de Ventas'},
        ),
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='ticket',
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.passenger'),
        ),
    ]
