# Generated by Django 5.0.6 on 2024-07-15 21:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_bus_options_alter_busstop_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('type', models.CharField(blank=True, choices=[('b', 'Bus'), ('t', 'Train')], default='t', max_length=1, verbose_name='type')),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
                ('enabled', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled')),
            ],
        ),
        migrations.RemoveField(
            model_name='journeystage',
            name='end_bus_stop',
        ),
        migrations.RemoveField(
            model_name='journeystage',
            name='start_bus_stop',
        ),
        migrations.RemoveField(
            model_name='journeystage',
            name='start_station',
        ),
        migrations.RemoveField(
            model_name='journeystage',
            name='end_station',
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['name'], 'verbose_name': 'Colectivo', 'verbose_name_plural': 'Colectivos'},
        ),
        migrations.AlterModelOptions(
            name='detailfoodorder',
            options={'ordering': ['receipt'], 'verbose_name': 'Detalle de la Orden de platos', 'verbose_name_plural': 'Detalles de la Orden de platos'},
        ),
        migrations.AlterModelOptions(
            name='detailsmerchandiseorder',
            options={'ordering': ['receipt'], 'verbose_name': 'Detalle de la Orden de mercadería', 'verbose_name_plural': 'Detalles de la Orden de mercadería'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['type'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorridos'},
        ),
        migrations.AlterModelOptions(
            name='journeyschedule',
            options={'ordering': ['journey'], 'verbose_name': 'Cronograma de Recorrido', 'verbose_name_plural': 'Cronogramas de Recorrido'},
        ),
        migrations.AlterModelOptions(
            name='journeystage',
            options={'ordering': ['order'], 'verbose_name': 'Etapa de Recorrido', 'verbose_name_plural': 'Etapas de Recorrido'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name'], 'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
        migrations.AlterModelOptions(
            name='merchandise',
            options={'ordering': ['name'], 'verbose_name': 'Mercaderia', 'verbose_name_plural': 'Mercaderias'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['dni_or_passport'], 'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['purchase_date'], 'verbose_name': 'Factura de Venta', 'verbose_name_plural': 'Facturas de Ventas'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number'], 'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.AlterModelOptions(
            name='seatcategory',
            options={'ordering': ['type'], 'verbose_name': 'Categoria de Asiento', 'verbose_name_plural': 'Categorias de Asiento'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.AlterModelOptions(
            name='ticketsales',
            options={'ordering': ['user'], 'verbose_name': 'Venta de Boletos', 'verbose_name_plural': 'Ventas de Boletos'},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['name'], 'verbose_name': 'Tren', 'verbose_name_plural': 'Trenes'},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='journeystage',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='journeystage',
            name='train',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='train',
        ),
        migrations.RemoveField(
            model_name='seatcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='train',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='detailfoodorder',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='detailfoodorder',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meal', verbose_name='meal'),
        ),
        migrations.AlterField(
            model_name='detailfoodorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='detailfoodorder',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.purchasereceipt', verbose_name='receipt'),
        ),
        migrations.AlterField(
            model_name='detailfoodorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit_price'),
        ),
        migrations.AlterField(
            model_name='detailsmerchandiseorder',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='detailsmerchandiseorder',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.merchandise', verbose_name='merchandise'),
        ),
        migrations.AlterField(
            model_name='detailsmerchandiseorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='detailsmerchandiseorder',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandises', to='core.purchasereceipt', verbose_name='receipt'),
        ),
        migrations.AlterField(
            model_name='detailsmerchandiseorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit_price'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='type',
            field=models.CharField(choices=[('TRAIN_ONLY', 'Train Only'), ('BUS_AND_TRAIN', 'Bus and Train')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='journeyschedule',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='arrival_time'),
        ),
        migrations.AlterField(
            model_name='journeyschedule',
            name='departure_time',
            field=models.DateTimeField(verbose_name='departure_time'),
        ),
        migrations.AlterField(
            model_name='journeyschedule',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='journeyschedule',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journey', verbose_name='journey'),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='duration',
            field=models.DurationField(verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.journey', verbose_name='journey'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='dni_or_passport',
            field=models.CharField(max_length=50, verbose_name='dni_or_passport'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='emergency_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='emergency_telephone'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('w', 'Female')], default='m', help_text='Genero del pasajero', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='origin_country',
            field=models.CharField(max_length=100, verbose_name='origin_country'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(max_length=255, verbose_name='payment_id'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='payment_status'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(max_length=50, verbose_name='payment_type'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticketsales', verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.passenger', verbose_name='passenger'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='purchase_date'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.seatcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10, verbose_name='seat_number'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger', verbose_name='passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.ticketsales', verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journeyschedule', verbose_name='schedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seat', verbose_name='seat'),
        ),
        migrations.AlterField(
            model_name='ticketsales',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='ticketsales',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ticketsales',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='purchase_date'),
        ),
        migrations.AlterField(
            model_name='ticketsales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='train',
            name='enabled',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='journeystage',
            name='arrival_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_stages', to='core.stops', verbose_name='arrival_stop'),
        ),
        migrations.AddField(
            model_name='journeystage',
            name='departure_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_stages', to='core.stops', verbose_name='departure_stop'),
        ),
        migrations.AddField(
            model_name='bus',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transport', verbose_name='transport'),
        ),
        migrations.AddField(
            model_name='journeystage',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transport', verbose_name='transport'),
        ),
        migrations.AddField(
            model_name='seat',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.transport', verbose_name='transport'),
        ),
        migrations.AddField(
            model_name='train',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transport', verbose_name='transport'),
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
