# Generated by Django 5.0.6 on 2024-07-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bus_options_alter_detailfoodorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='capacity',
        ),
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity'),
        ),
        migrations.AddField(
            model_name='train',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity'),
        ),
    ]
