# Generated by Django 5.0.6 on 2024-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Seleccione una imágen'),
        ),
    ]
