# Generated by Django 5.0.6 on 2024-05-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_autor_options_autor_foto_alter_autor_retrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['fechaDevolucion']},
        ),
    ]
