# Generated by Django 5.0.6 on 2024-06-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_ejemplar_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='foto',
        ),
    ]
