# Generated by Django 5.0.6 on 2024-06-15 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_ev', models.UUIDField(default=uuid.uuid4, help_text='ID único para cada evento', primary_key=True, serialize=False)),
                ('nomb_ev', models.CharField(max_length=200)),
                ('desc_ev', models.CharField(max_length=200)),
                ('fec_ini_ev', models.DateField(blank=True, null=True)),
                ('fec_fin_ev', models.DateField(blank=True, null=True)),
                ('pr_ev', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hab_ev', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado'), ('s', 'Suspendido'), ('f', 'Finalizado')], default='h', max_length=1)),
            ],
            options={
                'ordering': ['fec_ini_ev'],
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('cod_post_lc', models.UUIDField(default=uuid.uuid4, help_text='ID único para cada localidad', primary_key=True, serialize=False)),
                ('nomb_lc', models.CharField(max_length=200)),
                ('hab_lc', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'ordering': ['nomb_lc'],
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_pv', models.UUIDField(default=uuid.uuid4, help_text='ID único para cada provincia', primary_key=True, serialize=False)),
                ('nomb_pv', models.CharField(max_length=200)),
                ('hab_pv', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado')], default='h', max_length=1)),
            ],
            options={
                'ordering': ['nomb_pv'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('class_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad de clases')),
                ('status', models.CharField(choices=[('I', 'En etapa de inscripción'), ('P', 'En progreso'), ('F', 'Finalizado')], default='I', max_length=1, verbose_name='Estado')),
                ('teacher', models.ForeignKey(limit_choices_to={'groups__name': 'profesores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('present', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presente')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='LugaresDeEvento',
            fields=[
                ('id_le', models.UUIDField(default=uuid.uuid4, help_text='ID único para cada evento', primary_key=True, serialize=False)),
                ('desc_le', models.CharField(max_length=200)),
                ('tel_le', models.CharField(max_length=15)),
                ('lat_le', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng_le', models.DecimalField(decimal_places=7, max_digits=10)),
                ('hab_ev', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado'), ('s', 'Suspendido'), ('f', 'Finalizado')], default='h', max_length=1)),
                ('cod_post_lc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.localidades')),
            ],
            options={
                'ordering': ['id_le'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1')),
                ('mark_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2')),
                ('mark_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3')),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.AddField(
            model_name='localidades',
            name='id_pv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provincias'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Alumno Regular')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='students_registration', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_ve', models.UUIDField(default=uuid.uuid4, help_text='ID único para cada venta', primary_key=True, serialize=False)),
                ('pr_ve', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cli_ve', models.ForeignKey(limit_choices_to={'groups__name': 'clientes'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-id_ve'],
            },
        ),
    ]
