# Generated by Django 5.0.6 on 2024-06-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ventas_evt_ve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='pr_ev',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='pr_ve',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
