# Generated by Django 5.0.6 on 2024-06-16 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_eventos_options_alter_localidades_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id_bl', models.UUIDField(default=uuid.uuid4, help_text='ID único para cada venta', primary_key=True, serialize=False)),
                ('cli_bl', models.ForeignKey(limit_choices_to={'groups__name': 'clientes'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('evt_bl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eventos', verbose_name='Evento')),
                ('ve_bl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ventas', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-id_bl'],
            },
        ),
    ]
