# Generated by Django 5.0.6 on 2024-06-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boletos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletos',
            name='ve_bl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ventas', verbose_name='Venta'),
        ),
    ]
