# Generated by Django 5.0.6 on 2024-06-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_boletos_ve_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='hab_ev',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Desahabilitado'), ('s', 'Suspendido'), ('f', 'Finalizado'), ('a', 'Actualizado')], default='h', max_length=1),
        ),
    ]
