# Generated by Django 5.0.6 on 2024-06-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_eventos_hab_ev'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletos',
            name='enVenta_bl',
            field=models.BooleanField(default=False),
        ),
    ]
