# Generated by Django 5.0.6 on 2024-07-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
